// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8SRw5WwxZYwyuBTjEjz3lF59Gw9UhwUA',
    appId: '1:422624538509:web:678463f3dc7e7cc43cd7c4',
    messagingSenderId: '422624538509',
    projectId: 'auth-app-60cc3',
    authDomain: 'auth-app-60cc3.firebaseapp.com',
    storageBucket: 'auth-app-60cc3.firebasestorage.app',
    measurementId: 'G-BG9PC91SB1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgnhV44iOHkw6-EJRzoG1yah6umG3lxsI',
    appId: '1:422624538509:android:85e77c6cfcf2c8dc3cd7c4',
    messagingSenderId: '422624538509',
    projectId: 'auth-app-60cc3',
    storageBucket: 'auth-app-60cc3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9Qtq8s5BbDOnp6r_kLgTeOzqxtPUGcoE',
    appId: '1:422624538509:ios:f0dcfdcfa8fbe9443cd7c4',
    messagingSenderId: '422624538509',
    projectId: 'auth-app-60cc3',
    storageBucket: 'auth-app-60cc3.firebasestorage.app',
    iosClientId: '422624538509-c7cvm3lo5c2l2mo55nde2k34aqcpeg70.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterAuthApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9Qtq8s5BbDOnp6r_kLgTeOzqxtPUGcoE',
    appId: '1:422624538509:ios:f0dcfdcfa8fbe9443cd7c4',
    messagingSenderId: '422624538509',
    projectId: 'auth-app-60cc3',
    storageBucket: 'auth-app-60cc3.firebasestorage.app',
    iosClientId: '422624538509-c7cvm3lo5c2l2mo55nde2k34aqcpeg70.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterAuthApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB8SRw5WwxZYwyuBTjEjz3lF59Gw9UhwUA',
    appId: '1:422624538509:web:bd3e61423aed18863cd7c4',
    messagingSenderId: '422624538509',
    projectId: 'auth-app-60cc3',
    authDomain: 'auth-app-60cc3.firebaseapp.com',
    storageBucket: 'auth-app-60cc3.firebasestorage.app',
    measurementId: 'G-WGBFSCYV5Z',
  );
}
